export const Codes = {
  File: 'G000',
  TopologyOutsideRealm: 'G001',
  MissingEntryPoint: 'G002',
  DuplicateName: 'G003',
  TypeMismatch: 'G004',
  UndefinedVariable: 'G005',
  UndefinedMethod: 'G006',
  UndefinedType: 'G007',
  WrongArgCount: 'G008',
  ArgTypeMismatch: 'G009',
  ReturnTypeMismatch: 'G010',
  NewOnNonClass: 'G011',
  IndexOnNonCollection: 'G012',
  StaticOnInstance: 'G013',
  InstanceOnStatic: 'G014',
  AmbiguousOverload: 'G015',
  NoMatchingOverload: 'G016',
  UnknownIntrinsic: 'G017',
  DuplicateIntrinsic: 'G018',
  MissingIntrinsic: 'G019',
  MissingFloorBind: 'G020',
  ThrowsOutsideTry: 'G021',
  BreakOutsideLoop: 'G022',
  UnusedVariable: 'G023',
  UnreachableCode: 'G024',
  EmptyBlock: 'G025',
  RedundantReturn: 'G026',
  MissingReturn: 'G027',
  InvalidCast: 'G028',
  ConditionNotBool: 'G029',
  CallToEntry: 'G030',
  PanicOutsideKernel: 'G031',
  NotIterable: 'G032',
  UnsafeRequired: 'G033',
  NotAnLvalue: 'G034',
  PrivateMember: 'G035',
  DiagInRelease: 'G036',
  RefArgMismatch: 'G037',
  NoIndexSetter: 'G038',
  NonExhaustiveMatch: 'G039',
  StaticOnFreeFunc: 'G040',
  WrongAnnotationKind: 'G041',
  UnknownPreambleTarget: 'G042',
  ThreadModeNotAllowed: 'G043',
  Syntax: 'G044',
  AssignInExpr: 'G045',
  UnterminatedLiteral: 'G046',
  BadEscape: 'G047',
  BadAnnotation: 'G048',
  BadNumber: 'G049',
  MissingLet: 'G050',
  InvalidNesting: 'G051',
  TrailingComma: 'G052',
  BadDeclHeader: 'G053',
  CannotInfer: 'G054',
  KernelBlockInHosted: 'G055',
  MissingRealm: 'G056',
  ShadowedFunction: 'G057',
  MissingEntry: 'G058',
  DuplicateEntry: 'G059',
  MissingProcessMode: 'G060',
  BadEntrySignature: 'G061',
  DeferTransfer: 'G062',
  ModuleField: 'G063',
  MisplacedEnvironment: 'G064',
  ConflictingModifiers: 'G065',
  BadThrowsReturnType: 'G066',
  LifecycleThrows: 'G067',
  EntryOutsideKernel: 'G068',
  AmbiguousCall: 'G069',
  ShadowedVariable: 'G070',
  SelfAssignment: 'G071',
  NoEffect: 'G072',
  ConstantCondition: 'G073',
  RedundantCast: 'G074',
  DivisionByZero: 'G075',
  UnusedParameter: 'G076',
  UnreachableCase: 'G077',
  SelfComparison: 'G078',
  BadShiftCount: 'G079',
  MissingInterpolation: 'G080',
  AssignOutsideCatch: 'G081',
  CatchHandlerNoAssign: 'G082',
  IdentityPayloadComparison: 'G083',
  ImprecisePayloadComparison: 'G084',
  MissingRealmKeyword: 'G085',
  UnknownRealm: 'G086',
  ScopedNameNotVisible: 'G087',
  UnmarkedShadow: 'G088',
  ScopeNotEnclosing: 'G089',
  UnknownInScope: 'G090',
  ProcessWithoutThreads: 'G091',
  PartialOperatorSet: 'G092',
  UnsafeAllocatingTemporary: 'G093',
  ManagedFixedArray: 'G094',
  MixedSignedness: 'G095',
  CharArithmetic: 'G096',
  ExplicitTypeArgs: 'G097',
  UseBeforeAssignment: 'G098',
  DiscardedRetain: 'G099',
  UninitialisedProcessVar: 'G100',
  ReferenceCycle: 'G101',
} as const;

export type Code = typeof Codes[keyof typeof Codes];

export const CODE_SUMMARIES: Readonly<Record<string, string>> = {
  G000: 'file or project level problem: a missing file, a missing or duplicated @environment, a missing library module',
  G001: 'topology declared outside its realm or process',
  G002: 'the kernel realm declares no entry point',
  G003: 'duplicate name',
  G004: 'type mismatch',
  G005: 'undefined variable or name',
  G006: 'undefined method',
  G007: 'undefined type, uninferrable type argument, or a misuse of void',
  G008: 'wrong argument count',
  G009: 'argument type mismatch',
  G010: 'return type mismatch',
  G011: "'new' on something that is not a class",
  G012: 'indexing something that cannot be indexed',
  G013: 'a static member reached through an instance',
  G014: 'an instance member reached through the type',
  G015: 'ambiguous overload',
  G016: 'no matching overload',
  G017: 'unknown @intrinsic role or @builtin slot',
  G018: 'that role or slot is already bound',
  G019: 'a required intrinsic is not bound anywhere in the build',
  G020: 'the environment preamble provides no definition of a floor symbol',
  G021: 'a throwing call outside try/throws/catch, or nested in a larger expression',
  G022: 'break or continue outside a loop',
  G023: 'unused variable',
  G024: 'unreachable code',
  G025: 'empty block body',
  G026: 'redundant trailing return',
  G027: 'the function does not return on every path',
  G028: 'invalid cast',
  G029: 'the condition is not bool',
  G030: 'a call to, or the address of, an entry point',
  G031: 'panic outside the kernel realm',
  G032: 'not iterable with for..in',
  G033: 'an unsafe block is required',
  G034: 'not an lvalue',
  G035: 'a private member accessed from outside',
  G036: 'debug or panic in a release build',
  G037: 'ref argument mismatch',
  G038: 'index setter or getter missing',
  G039: 'non-exhaustive match',
  G040: "'static' on a free function",
  G041: 'annotation on the wrong kind of declaration',
  G042: 'unknown @preamble target',
  G043: 'foreground or background on a thread',
  G044: 'syntax error',
  G045: 'assignment used as an expression',
  G046: 'unterminated literal or comment',
  G047: 'unrecognised escape sequence',
  G048: 'bad or unknown annotation',
  G049: 'malformed numeric literal',
  G050: "missing 'let'",
  G051: 'invalid nesting',
  G052: 'trailing comma',
  G053: 'bad declaration header',
  G054: 'cannot infer a type',
  G055: 'a kernel realm block in a Hosted build',
  G056: 'no userspace realm in a Hosted build',
  G057: 'a file-local function displaces an imported one of the same name',
  G058: 'the userspace realm declares no entry func',
  G059: 'the realm declares more than one entry func',
  G060: 'the process declaration is missing its mode, or writes it after the name',
  G061: 'bad entry signature',
  G062: 'a defer body transfers control',
  G063: 'a module declares a field',
  G064: '@environment inside a realm block',
  G065: 'conflicting or duplicated modifiers',
  G066: 'unsupported throws return type',
  G067: '_init or _deinit declared throws',
  G068: 'entry func outside the kernel realm, or inside a process',
  G069: 'ambiguous call across files',
  G070: 'shadowed variable',
  G071: 'self-assignment',
  G072: 'expression statement with no effect',
  G073: 'constant condition',
  G074: 'redundant cast',
  G075: 'integer division or remainder by literal zero',
  G076: 'unused parameter',
  G077: 'unreachable case or redundant default',
  G078: 'a value compared against itself',
  G079: 'shift count out of range',
  G080: 'a string that looks like it should have been interpolated',
  G081: "'assign' outside a catch handler",
  G082: 'a catch handler can finish without supplying a value',
  G083: 'a union comparison compares a payload by identity',
  G084: 'a union comparison compares a float payload with ==',
  G085: "'kernel' written without 'realm'",
  G086: 'unknown realm name',
  G087: 'the name is declared inside a scope that is not visible here',
  G088: 'unmarked shadow, or @shadows that displaces nothing',
  G089: 'the scope qualifier does not enclose this code, or names no scope',
  G090: 'the qualified scope declares no such name',
  G091: 'the process declares no threads',
  G092: 'partial relational operator set',
  G093: 'an unsafe block allocates a managed temporary',
  G094: 'a fixed array of a managed element type',
  G095: 'mixed signed and unsigned operands',
  G096: 'arithmetic on two chars',
  G097: 'explicit type arguments at a call site',
  G098: 'read before assignment',
  G099: 'discarded retain',
  G100: 'a process variable with no initial value, or a catch handler that returns',
  G101: 'reference cycle',
};

export interface Span {
  start: number;
  length: number;
}

export const NoSpan: Span = { start: -1, length: 0 };

export class ParseError extends Error {
  constructor(
    public readonly span: Span,
    message: string,
    public readonly code: string = Codes.Syntax,
    public readonly hints: string[] = [],
  ) {
    super(message);
  }
}
